services:
  - type: web
    name: news-collector
    runtime: static
    buildCommand: ""
    staticPublishPath: ./docs
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /data/*
        name: Cache-Control
        value: no-cache
    autoDeploy: true
